INSERT INTO COURSE(COURSE_ID,COURSE_NAME,COURSE_CODE,SEMESTER,DEPARTMENT_ID) VALUES (1,'ScalableServices', 'SS', 1,1);
INSERT INTO COURSE(COURSE_ID,COURSE_NAME,COURSE_CODE,SEMESTER,DEPARTMENT_ID) VALUES (2,'Open Source Software', 'OSSE', 2,1);
INSERT INTO COURSE(COURSE_ID,COURSE_NAME,COURSE_CODE,SEMESTER,DEPARTMENT_ID) VALUES (3,'Software Architecture', 'SA', 1,2);
INSERT INTO COURSE(COURSE_ID,COURSE_NAME,COURSE_CODE,SEMESTER,DEPARTMENT_ID) VALUES (4,'Object Oriented And Design', 'OOAD', 2,2);